apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: data-validation-task
spec:
  steps:
  - name: data-validation-task
    image: 566373416292.dkr.ecr.us-east-1.amazonaws.com/ecom_data_validation:1
    computeResources:
        limits:
          cpu: 800m
          memory: 2Gi
        requests:
          cpu: 500m
          memory: 1Gi