apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: embedded-trigger-listener
spec:
  serviceAccountName: train-pipeline-trigger-sa
  triggers:
    - name: train-pipeline-trigger
      bindings:
        - name: train-pipeline-binding
      template:
        ref: trigger-pipeline-template
